### ISSUE TITLE
Possible to pick file with persistent uri?

### ISSUE THREAD

**Issue by AhsanSarwar45** [chaudharydeepanshu/pick_or_save#5]
Hi, love your package!
I was wondering if its possible to get persistent uri to picked files? I want to store the picked files uris (pointing to audio files) in the app, and play those audio files later. Is it possible, or is it a limitation of Android?

**Comment by chaudharydeepanshu** [comment]
Sorry for the very late reply.

For your and other's future reference, yes you should be able to store the picked files URIs and use them later. But I would suggest using the `directoryPicker()` in this package for this task.

**Comment by azeem-swr** [comment]
@chaudharydeepanshu Hi, you mentioned directoryPicker for this use case, but I don't think reading files the directory picked works at all. Is there any possible way to pick a directory and read the files within that directory later?
